env:
  SONAR_LOGIN:  ${{ secrets.SONAR_LOGIN }}
  GOLANG_VERSION: '1.16.4'  
on:
  push:    
    branches:   
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    name: Build
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
        #we can even remove this step if our self-hosted container already have it installed.     
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.12'
          distribution: 'adopt'
        #we can even remove this step if our self-hosted container already have it installed.       
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}    
      - name: buildAllOneStep
        run: ./gradlew --info showVersionDetails goTest sonarqube    #this is also the command to run locally. no sonar installation needed.      
        
      